'use strict';

// Ordem de batalha — Guerra das Malvinas/Falklands (1982)
// Azul = Argentina (defende as ilhas já ocupadas + litoral patagônico)
// Vermelho = Reino Unido (força-tarefa expedicionária vinda de Ascensão)
// Fonte: NWC "War at Sea" Falklands/Malvinas OAF Docs (Reino Unido v1.4, Argentina v1.4.1)
// v2: revisão do autor a partir dos cadernos originais (ver planilha "Divergencias e Notas") —
// unidades desmembradas por escalao/grupo real do OAF, colunas AAM/Minas, echelon e LP de referência.
const ORDER_OF_BATTLE = {
  "forces": {
    "blue": [
      {
        "id":"BLUE-VM","name":"GT Porta-Aviões","category":"surface",
        "composition":[{"type":"navio_aeródromo","quantity":1},{"type":"helicoptero_ASW","quantity":2},{"type":"helicoptero_ASup","quantity":2}],
        "stayingPower":8,"movement":4,
        "detectionRange":{"surface":3,"air":2,"submarine":1,"land":1},
        "attackRange":{"surface":1,"air":1,"submarine":1,"land":0},
        "weapons":{},
        "capabilities":{"navalGun":2,"airDefense":1,"asw":2},
        "position":{"col":5,"row":1},
        "echelon":"START",
        "notes":"ARA Veinticinco de Mayo (ex-HMS Venerable). Porta-aviões leve a vapor. Base da 1ª Esquadrilha de A-4Q."
      },
      {
        "id":"BLUE-VM-AIR","name":"3ª Esq. Aeronaval A-4Q","category":"air",
        "composition":[{"type":"ataque","quantity":8}],
        "stayingPower":4,"movement":9,
        "detectionRange":{"surface":2,"air":1,"submarine":0,"land":1},
        "attackRange":{"surface":2,"air":0,"submarine":0,"land":2},
        "weapons":{"lacm":{"quantity":6,"range":2}},
        "capabilities":{"airAttack":6},
        "position":{"col":5,"row":1},
        "embarked":"BLUE-VM",
        "echelon":"START",
        "notes":"8× A-4Q Skyhawk da 3ª Esquadrilha Aeronaval de Caça e Ataque, embarcados no ARA Veinticinco de Mayo. Armamento de bombas não guiadas (coluna LACM), não mísseis."
      },
      {
        "id":"BLUE-VE","name":"Escolta GT-PA","category":"surface",
        "composition":[{"type":"destroyer","quantity":2},{"type":"helicoptero_ASup","quantity":1}],
        "stayingPower":5,"movement":4,
        "detectionRange":{"surface":2,"air":2,"submarine":1,"land":1},
        "attackRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "weapons":{"ascm":{"quantity":2,"range":6},"mss":{"quantity":6,"range":3}},
        "capabilities":{"navalGun":1,"airDefense":2,"asw":2},
        "position":{"col":6,"row":1},
        "echelon":"START",
        "notes":"ARA Hércules + ARA Santísima Trinidad (Type 42, Sea Dart/Exocet). Escolta principal do GT porta-aviões."
      },
      {
        "id":"BLUE-BV","name":"Esquadra de Corvetas","category":"surface",
        "composition":[{"type":"corveta","quantity":3}],
        "stayingPower":3,"movement":4,
        "detectionRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "attackRange":{"surface":2,"air":1,"submarine":1,"land":0},
        "weapons":{"ascm":{"quantity":3,"range":6}},
        "capabilities":{"navalGun":2,"airDefense":3,"asw":2},
        "position":{"col":6,"row":2},
        "echelon":"START",
        "notes":"ARA Drummond, Guerrico e Granville (classe A69). Guerrico avariada em Grytviken, 3 abr 1982."
      },
      {
        "id":"BLUE-B","name":"Belgrano","category":"surface",
        "composition":[{"type":"cruzador","quantity":1}],
        "stayingPower":6,"movement":4,
        "detectionRange":{"surface":2,"air":1,"submarine":0,"land":1},
        "attackRange":{"surface":3,"air":0,"submarine":0,"land":2},
        "weapons":{},
        "capabilities":{"navalGun":8,"airDefense":2},
        "position":{"col":5,"row":7},
        "echelon":"START",
        "notes":"ARA General Belgrano (ex-USS Phoenix). Forte artilharia de 6\". Afundado por torpedos em 2 mai 1982 — 323 mortos."
      },
      {
        "id":"BLUE-BS","name":"Escolta Belgrano","category":"surface",
        "composition":[{"type":"destroyer","quantity":2}],
        "stayingPower":3,"movement":4,
        "detectionRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "attackRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "weapons":{"ascm":{"quantity":2,"range":6}},
        "capabilities":{"navalGun":6,"airDefense":2,"asw":2},
        "position":{"col":5,"row":7},
        "echelon":"START",
        "notes":"ARA Hipólito Bouchard + ARA Piedrabuena (ex-Fletcher/Sumner). Escolta do Belgrano."
      },
      {
        "id":"BLUE-LOG-1","name":"Petroleiro ARA Punta Médanos","category":"surface",
        "composition":[{"type":"navio_tanque","quantity":1}],
        "stayingPower":4,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":4,"row":1},
        "echelon":"START",
        "notes":"ARA Punta Médanos. Petroleiro de esquadra do GT porta-aviões."
      },
      {
        "id":"BLUE-LOG-2","name":"Petroleiro ARA Punta Delgada","category":"surface",
        "composition":[{"type":"navio_tanque","quantity":1}],
        "stayingPower":4,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":4,"row":7},
        "echelon":"START",
        "notes":"ARA Punta Delgada (O2 do caderno). Abastece o GT Belgrano; mais lento que os navios que apoia."
      },
      {
        "id":"BLUE-LOG-3","name":"Petroleiro de Serviço Geral","category":"surface",
        "composition":[{"type":"navio_tanque","quantity":1}],
        "stayingPower":4,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":1,"row":5},
        "echelon":"START",
        "notes":"O3 do caderno — único petroleiro argentino que começa completamente cheio, atracado em Río Gallegos."
      },
      {
        "id":"BLUE-SUB-1","name":"Santa Fe","category":"submarine",
        "composition":[{"type":"submarino_convencional","quantity":1}],
        "stayingPower":4,"movement":2,
        "detectionRange":{"surface":2,"air":0,"submarine":1,"land":0},
        "attackRange":{"surface":2,"air":0,"submarine":1,"land":0},
        "weapons":{"torpedo":{"quantity":6,"range":2}},
        "capabilities":{},
        "position":{"col":17,"row":7},
        "echelon":"START",
        "notes":"ARA Santa Fe (ex-USS Catfish, classe Guppy). Avariada e encalhada em Grytviken, 25 abr 1982."
      },
      {
        "id":"BLUE-SUB-2","name":"San Luis","category":"submarine",
        "composition":[{"type":"submarino_convencional","quantity":1}],
        "stayingPower":4,"movement":2,
        "detectionRange":{"surface":2,"air":0,"submarine":1,"land":0},
        "attackRange":{"surface":2,"air":0,"submarine":1,"land":0},
        "weapons":{"torpedo":{"quantity":6,"range":2}},
        "capabilities":{},
        "position":{"col":8,"row":4},
        "echelon":"START",
        "notes":"ARA San Luis (Type 209). Realizou vários ataques frustrados contra a Força-Tarefa britânica."
      },
      {
        "id":"BLUE-PAT","name":"Patrulha Costeira","category":"surface",
        "composition":[{"type":"navio_patrulha","quantity":4}],
        "stayingPower":4,"movement":4,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":1},
        "attackRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{"airDefense":1},
        "position":{"col":7,"row":5},
        "echelon":"START",
        "notes":"Lanchas Z-28 (Islas Malvinas, Río Iguazú) + patrulheiros Dabur. Vigilância costeira das ilhas."
      },
      {
        "id":"BLUE-MCM","name":"Grupo Caça-Minas","category":"surface",
        "composition":[{"type":"navio_patrulha","quantity":4}],
        "stayingPower":5,"movement":2,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{"mines":{"quantity":2}},
        "capabilities":{},
        "position":{"col":1,"row":5},
        "echelon":"START",
        "notes":"Grupos M1/M2. M1 inicia atracado em Río Gallegos e M2 nas imediações do porto, conforme o caderno. Cada um pode lançar um campo minado adicional (turnos 3 e 4 no jogo original)."
      },
      {
        "id":"BLUE-CAMPO-MIN","name":"Campo Minado de Porto Argentino","category":"land",
        "composition":[{"type":"campo_minado","quantity":1}],
        "stayingPower":2,"movement":0,
        "detectionRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{"mines":{"quantity":1}},
        "capabilities":{},
        "position":{"col":7,"row":4},
        "echelon":"START",
        "notes":"Campo minado inicial, lançado antes do começo da partida nas aproximações de Porto Argentino. Só pode ser varrido por caça-minas; detém o movimento de quem o cruza."
      },
      {
        "id":"BLUE-ISR","name":"Piquete de Vigilância","category":"surface",
        "composition":[{"type":"navio_patrulha","quantity":5}],
        "stayingPower":3,"movement":2,
        "detectionRange":{"surface":3,"air":1,"submarine":0,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":9,"row":3},
        "echelon":"START",
        "notes":"Traineiras e mercantes civis reconvertidos em piquetes de vigilância (Narwal, Alejandra, Costanza e outros)."
      },
      {
        "id":"BLUE-LG","name":"Grupo de Desembarque","category":"surface",
        "composition":[{"type":"navio_desembarque","quantity":2},{"type":"navio_doca","quantity":1}],
        "stayingPower":6,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":1},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "weapons":{},
        "capabilities":{"airDefense":1},
        "position":{"col":6,"row":5},
        "echelon":"START",
        "notes":"2× LST + 1 rebocador de alto-mar. Liga o continente a Porto Argentino com reforços e suprimentos."
      },
      {
        "id":"BLUE-CARGO","name":"Cargueiros de Suprimento","category":"surface",
        "composition":[{"type":"navio_logistico","quantity":3}],
        "stayingPower":6,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":1,"row":5},
        "echelon":"START",
        "logisticsPoints":12,
        "notes":"Formosa/Río Carcarañá, Río Cincel/Mar del Norte, Lago Argentino/Puerto Rosales. 4 LP por navio; atracados em Río Gallegos no início."
      },
      {
        "id":"BLUE-SOF","name":"Comandos Anfíbios","category":"specops",
        "composition":[{"type":"operacoes_especiais","quantity":1}],
        "stayingPower":2,"movement":2,
        "detectionRange":{"surface":0,"air":0,"submarine":0,"land":1},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":2},
        "weapons":{"raid":{"quantity":3,"range":2}},
        "capabilities":{},
        "position":{"col":8,"row":4},
        "hostId":"BLUE-SUB-2",
        "stealthy":true,
        "echelon":"START",
        "notes":"Comandos Anfíbios / Buzos Tácticos. Embarcados no ARA San Luis."
      },
      {
        "id":"BLUE-CACA","name":"Mirage III / Dagger","category":"air",
        "composition":[{"type":"caca","quantity":23}],
        "stayingPower":8,"movement":6,
        "detectionRange":{"surface":1,"air":2,"submarine":0,"land":1},
        "attackRange":{"surface":1,"air":2,"submarine":0,"land":1},
        "weapons":{"aam":{"quantity":8,"range":1}},
        "capabilities":{"airAttack":4},
        "position":{"col":1,"row":3},
        "echelon":"START",
        "notes":"8× Mirage IIIEA (Grupo 8) + 15× Dagger (Grupos 6). Base em San Julián/Río Gallegos. Alcance limitado sobre as ilhas — poucos minutos de permanência."
      },
      {
        "id":"BLUE-ATQ-SKYHAWK","name":"A-4B/C Skyhawk","category":"air",
        "composition":[{"type":"ataque","quantity":31}],
        "stayingPower":10,"movement":6,
        "detectionRange":{"surface":2,"air":1,"submarine":0,"land":1},
        "attackRange":{"surface":2,"air":0,"submarine":0,"land":2},
        "weapons":{"lacm":{"quantity":10,"range":2}},
        "capabilities":{"airAttack":9},
        "position":{"col":1,"row":5},
        "echelon":"START",
        "notes":"A-4B (Grupo 5, Río Gallegos) + A-4C (Grupo 4, San Julián). Bombas não guiadas (coluna LACM). Depende do KC-130H para alcançar as ilhas com margem de combate."
      },
      {
        "id":"BLUE-ATQ-ETEN","name":"Super Étendard","category":"air",
        "composition":[{"type":"ataque","quantity":5}],
        "stayingPower":3,"movement":7,
        "detectionRange":{"surface":2,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":3,"air":0,"submarine":0,"land":0},
        "weapons":{"ascm":{"quantity":5,"range":6}},
        "capabilities":{"airAttack":2},
        "position":{"col":2,"row":7},
        "echelon":"START",
        "notes":"2ª Esquadrilha Aeronaval de Caça e Ataque, Río Grande. 5× AM39 Exocet disponíveis em toda a guerra, sem reposição (o caderno original cita 4)."
      },
      {
        "id":"BLUE-BOM-CANB","name":"Canberra","category":"air",
        "composition":[{"type":"ataque","quantity":7}],
        "stayingPower":5,"movement":6,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "attackRange":{"surface":2,"air":0,"submarine":0,"land":2},
        "weapons":{"lacm":{"quantity":4,"range":8}},
        "capabilities":{"airAttack":3},
        "position":{"col":0,"row":1},
        "echelon":"START",
        "notes":"Grupo 2 de Bombardeo. Bombardeiro de longo alcance, baixa sobrevivência diante de caças modernos."
      },
      {
        "id":"BLUE-ISR-AIR","name":"Lear Jet / SP-2 Neptune","category":"air",
        "composition":[{"type":"patrulha_maritima","quantity":6}],
        "stayingPower":3,"movement":10,
        "detectionRange":{"surface":4,"air":1,"submarine":1,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":1,"row":3},
        "echelon":"START",
        "notes":"Lear Jet 35A (Esc. Fénix) + SP-2H Neptune. ISR de longo alcance, sem armamento."
      },
      {
        "id":"BLUE-PUCARA","name":"Pucará (Porto Argentino)","category":"air",
        "composition":[{"type":"ataque","quantity":8}],
        "stayingPower":8,"movement":4,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":2},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":2},
        "weapons":{},
        "capabilities":{"airAttack":5},
        "position":{"col":7,"row":4},
        "echelon":"START",
        "notes":"IA-58 Pucará baseados no aeródromo de Porto Argentino. Ataque ao solo, baixa velocidade."
      },
      {
        "id":"BLUE-PUCARA-2","name":"Pucará (Ganso Verde / Pebble)","category":"air",
        "composition":[{"type":"ataque","quantity":16}],
        "stayingPower":8,"movement":4,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":2},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":2},
        "weapons":{},
        "capabilities":{"airAttack":5},
        "position":{"col":6,"row":5},
        "echelon":"START (inclui reforços dos turnos 3 e 4)",
        "notes":"Esquadrilhas de Ganso Verde e Ilha Pebble, já incluindo os reforços que no jogo original chegavam nos turnos 3 e 4. Seis aeronaves foram destruídas no raid do SAS em Pebble, 15 mai 1982."
      },
      {
        "id":"BLUE-GARR-STANLEY","name":"Guarnição de Porto Argentino","category":"land",
        "composition":[{"type":"infantaria","quantity":5},{"type":"bateria_ada","quantity":4}],
        "stayingPower":14,"movement":1,
        "detectionRange":{"surface":1,"air":2,"submarine":0,"land":3},
        "attackRange":{"surface":2,"air":0,"submarine":0,"land":3},
        "weapons":{},
        "capabilities":{"navalGun":4,"airDefense":5},
        "position":{"col":7,"row":4},
        "echelon":"START",
        "logisticsPoints":4,
        "notes":"10ª Brigada de Infantería (3º, 6º, 7º, 25º RI) + 5º Batalhão de Infantaria de Marinha. ~5.000 efetivos. Consome 1 LP por turno; a zero, perde um dado de capacidade por turno."
      },
      {
        "id":"BLUE-EXOCET-STANLEY","name":"Bateria Exocet MM38","category":"land",
        "composition":[{"type":"bateria_costeira","quantity":1}],
        "stayingPower":3,"movement":0,
        "detectionRange":{"surface":2,"air":0,"submarine":0,"land":0},
        "attackRange":{"surface":3,"air":0,"submarine":0,"land":0},
        "weapons":{"ascm":{"quantity":2,"range":3}},
        "capabilities":{},
        "position":{"col":7,"row":4},
        "echelon":"START",
        "notes":"2× lançadores MM38 Exocet improvisados por técnicos navais. Atingiu o HMS Glamorgan em 12 jun 1982 — sem reabastecimento possível."
      },
      {
        "id":"BLUE-GARR-GOOSE","name":"Guarnição de Ganso Verde","category":"land",
        "composition":[{"type":"infantaria","quantity":2},{"type":"bateria_ada","quantity":2}],
        "stayingPower":12,"movement":1,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":2},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":2},
        "weapons":{},
        "capabilities":{"navalGun":1,"airDefense":2},
        "position":{"col":6,"row":5},
        "echelon":"START",
        "notes":"12º Regimiento de Infantería (Cia A + B). Defende Ganso Verde/Prado do Ganso."
      },
      {
        "id":"BLUE-GARR-PEBBLE","name":"Guarnição da Ilha Pebble","category":"land",
        "composition":[{"type":"infantaria","quantity":1}],
        "stayingPower":2,"movement":1,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "weapons":{},
        "capabilities":{},
        "position":{"col":6,"row":5},
        "echelon":"START",
        "notes":"Força de segurança do aeródromo da Ilha Pebble. Alvo do raid do SAS em 15 mai 1982."
      },
      {
        "id":"BLUE-GARR-WEST","name":"Guarnição da Falkland Ocidental","category":"land",
        "composition":[{"type":"infantaria","quantity":2}],
        "stayingPower":4,"movement":1,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":1},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "weapons":{},
        "capabilities":{"airDefense":1},
        "position":{"col":5,"row":5},
        "echelon":"START",
        "notes":"Forças de Segurança de Port Howard e Fox Bay, Falkland Ocidental."
      },
      {
        "id":"BLUE-GARR-SG","name":"Guarnição da Geórgia do Sul","category":"land",
        "composition":[{"type":"infantaria","quantity":1}],
        "stayingPower":2,"movement":1,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "weapons":{},
        "capabilities":{},
        "position":{"col":19,"row":7},
        "echelon":"START",
        "notes":"Pequeno destacamento em Grytviken/Leith. Capturado em 25 abr 1982 após ataque naval e aéreo britânico."
      },
      {
        "id":"BLUE-AERO-N","name":"BAM Comodoro Rivadavia","category":"land",
        "composition":[{"type":"aeroporto","quantity":1}],
        "stayingPower":12,"movement":0,
        "detectionRange":{"surface":1,"air":2,"submarine":0,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":0,"row":1},
        "echelon":"START",
        "notes":"Base Aérea Militar de Comodoro Rivadavia. Sede dos Canberra do Grupo 2 e dos KC-130H."
      },
      {
        "id":"BLUE-TANKER-AIR","name":"KC-130H Hércules","category":"air",
        "composition":[{"type":"reabastecedor","quantity":2}],
        "stayingPower":2,"movement":10,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":0,"row":1},
        "echelon":"START",
        "notes":"2× KC-130H do Grupo 1 de Transporte Aéreo. Reabastecimento em voo de A-4 e Super Étendard — sem eles, os ataques continentais perdem tempo útil sobre o alvo."
      },
      {
        "id":"BLUE-AERO-SJ","name":"BAM San Julián","category":"land",
        "composition":[{"type":"aeroporto","quantity":1}],
        "stayingPower":12,"movement":0,
        "detectionRange":{"surface":1,"air":2,"submarine":0,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":1,"row":3},
        "echelon":"START",
        "notes":"Base dos Dagger e de parte dos A-4C, além dos Lear Jet de ISR."
      },
      {
        "id":"BLUE-AERO-RG","name":"BAM Río Gallegos","category":"land",
        "composition":[{"type":"aeroporto","quantity":1}],
        "stayingPower":12,"movement":0,
        "detectionRange":{"surface":1,"air":2,"submarine":0,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":1,"row":5},
        "echelon":"START",
        "notes":"Principal base continental de A-4B/C Skyhawk."
      },
      {
        "id":"BLUE-PORTO-RG","name":"Porto de Río Gallegos","category":"land",
        "composition":[{"type":"porto","quantity":1}],
        "stayingPower":10,"movement":0,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":1,"row":5},
        "echelon":"START",
        "notes":"Hub logístico continental. Reabastece navios argentinos em operação."
      },
      {
        "id":"BLUE-AERO-RGR","name":"BAM Río Grande","category":"land",
        "composition":[{"type":"aeroporto","quantity":1}],
        "stayingPower":12,"movement":0,
        "detectionRange":{"surface":1,"air":2,"submarine":0,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":2,"row":7},
        "echelon":"START",
        "notes":"Base dos Super Étendard e A-4Q. A mais próxima das ilhas entre as bases continentais."
      }
    ],
    "red": [
      {
        "id":"RED-HERMES","name":"HMS Hermes","category":"surface",
        "composition":[{"type":"navio_aeródromo","quantity":1},{"type":"helicoptero_ASW","quantity":6},{"type":"helicoptero_ASup","quantity":2}],
        "stayingPower":10,"movement":4,
        "detectionRange":{"surface":3,"air":2,"submarine":1,"land":1},
        "attackRange":{"surface":1,"air":1,"submarine":1,"land":0},
        "weapons":{},
        "capabilities":{"airDefense":1,"asw":2},
        "position":{"col":13,"row":3},
        "echelon":"START",
        "notes":"Nau capitânia da Força-Tarefa. Casco de 1959, blindagem espessa (maior sobrevivência que o Invincible) e grupo aéreo maior. Alvo prioritário dos Exocet."
      },
      {
        "id":"RED-HAR-1","name":"800 NAS Sea Harrier","category":"air",
        "composition":[{"type":"caca","quantity":12}],
        "stayingPower":6,"movement":10,
        "detectionRange":{"surface":2,"air":2,"submarine":0,"land":1},
        "attackRange":{"surface":2,"air":2,"submarine":0,"land":2},
        "weapons":{"aam":{"quantity":8,"range":2}},
        "capabilities":{"airDefense":9,"airAttack":6},
        "position":{"col":13,"row":3},
        "embarked":"RED-HERMES",
        "echelon":"START",
        "notes":"12× Sea Harrier FRS.1 do 800 NAS, com AIM-9L Sidewinder. CAP e ataque ao solo. Nenhuma perda em combate ar-ar durante toda a guerra."
      },
      {
        "id":"RED-INVINCIBLE","name":"HMS Invincible","category":"surface",
        "composition":[{"type":"navio_aeródromo","quantity":1},{"type":"helicoptero_ASW","quantity":4},{"type":"helicoptero_ASup","quantity":2}],
        "stayingPower":8,"movement":4,
        "detectionRange":{"surface":3,"air":2,"submarine":1,"land":1},
        "attackRange":{"surface":1,"air":1,"submarine":1,"land":0},
        "weapons":{},
        "capabilities":{"airDefense":1,"asw":2},
        "position":{"col":13,"row":2},
        "echelon":"START",
        "notes":"Porta-aviões leve (\"through-deck cruiser\"), mais moderno e resistente que o Hermes, grupo aéreo menor."
      },
      {
        "id":"RED-HAR-2","name":"801 NAS Sea Harrier","category":"air",
        "composition":[{"type":"caca","quantity":9}],
        "stayingPower":5,"movement":10,
        "detectionRange":{"surface":2,"air":2,"submarine":0,"land":1},
        "attackRange":{"surface":2,"air":2,"submarine":0,"land":2},
        "weapons":{"aam":{"quantity":6,"range":2}},
        "capabilities":{"airDefense":7,"airAttack":5},
        "position":{"col":13,"row":2},
        "embarked":"RED-INVINCIBLE",
        "echelon":"START",
        "notes":"9× Sea Harrier FRS.1 do 801 NAS, com AIM-9L. Reforçado pelos Harriers de reposição do Atlantic Conveyor."
      },
      {
        "id":"RED-SCR-1","name":"Screen 1","category":"surface",
        "composition":[{"type":"destroyer","quantity":2}],
        "stayingPower":7,"movement":4,
        "detectionRange":{"surface":2,"air":2,"submarine":1,"land":1},
        "attackRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "weapons":{"mss":{"quantity":6,"range":3}},
        "capabilities":{"navalGun":1,"airDefense":2,"asw":2},
        "position":{"col":13,"row":3},
        "echelon":"START",
        "notes":"HMS Glasgow + HMS Sheffield (Type 42, Sea Dart). Sem Exocet — ao contrário do caderno original, que atribui 2 a este grupo. Sheffield afundado por Exocet em 4 mai 1982 — 20 mortos."
      },
      {
        "id":"RED-SCR-2","name":"Screen 2","category":"surface",
        "composition":[{"type":"destroyer","quantity":1},{"type":"fragata","quantity":1}],
        "stayingPower":5,"movement":4,
        "detectionRange":{"surface":2,"air":2,"submarine":1,"land":1},
        "attackRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "weapons":{"ascm":{"quantity":2,"range":3},"mss":{"quantity":3,"range":3}},
        "capabilities":{"navalGun":1,"airDefense":2,"asw":2},
        "position":{"col":13,"row":4},
        "echelon":"START",
        "notes":"HMS Coventry (Type 42, Sea Dart) + HMS Arrow (Type 21, Exocet). Coventry afundado em 25 mai após 3 ataques aéreos, abatendo 2 aeronaves antes."
      },
      {
        "id":"RED-ESC-1","name":"Escort 1","category":"surface",
        "composition":[{"type":"destroyer","quantity":1},{"type":"fragata","quantity":1}],
        "stayingPower":5,"movement":4,
        "detectionRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "attackRange":{"surface":2,"air":1,"submarine":1,"land":2},
        "weapons":{"ascm":{"quantity":2,"range":6},"mss":{"quantity":3,"range":3}},
        "capabilities":{"navalGun":1,"airDefense":2,"asw":2},
        "position":{"col":12,"row":3},
        "echelon":"START",
        "notes":"HMS Glamorgan (County, Exocet + Sea Slug) + HMS Broadsword (Type 22, Sea Wolf). Glamorgan sobreviveu a um Exocet lançado de terra em 12 jun — 13 mortos."
      },
      {
        "id":"RED-ESC-2","name":"Escort 2","category":"surface",
        "composition":[{"type":"fragata","quantity":2}],
        "stayingPower":4,"movement":4,
        "detectionRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "attackRange":{"surface":1,"air":0,"submarine":1,"land":1},
        "weapons":{"ascm":{"quantity":2,"range":6}},
        "capabilities":{"navalGun":1,"airDefense":2,"asw":2},
        "position":{"col":12,"row":4},
        "echelon":"START",
        "notes":"HMS Yarmouth + HMS Alacrity (Leander/Type 21). Sem míssil dual-role — mais vulnerável ao ataque aéreo."
      },
      {
        "id":"RED-SUB-CONQ","name":"HMS Conqueror","category":"submarine",
        "composition":[{"type":"submarino_nuclear","quantity":1}],
        "stayingPower":5,"movement":4,
        "detectionRange":{"surface":3,"air":0,"submarine":2,"land":0},
        "attackRange":{"surface":3,"air":0,"submarine":2,"land":0},
        "weapons":{"torpedo":{"quantity":9,"range":2}},
        "capabilities":{},
        "position":{"col":5,"row":8},
        "echelon":"START",
        "notes":"SSN classe Churchill. Afundou o ARA General Belgrano em 2 mai 1982 — primeiro ataque de submarino nuclear da história."
      },
      {
        "id":"RED-SUB-SPART","name":"HMS Spartan","category":"submarine",
        "composition":[{"type":"submarino_nuclear","quantity":1}],
        "stayingPower":5,"movement":4,
        "detectionRange":{"surface":3,"air":0,"submarine":2,"land":0},
        "attackRange":{"surface":3,"air":0,"submarine":2,"land":0},
        "weapons":{"torpedo":{"quantity":9,"range":2}},
        "capabilities":{},
        "position":{"col":8,"row":5},
        "echelon":"START",
        "notes":"SSN classe Swiftsure. Um dos primeiros submarinos a chegar à zona de exclusão, em 12 abr 1982."
      },
      {
        "id":"RED-SUB-SPLEN","name":"HMS Splendid","category":"submarine",
        "composition":[{"type":"submarino_nuclear","quantity":1}],
        "stayingPower":5,"movement":4,
        "detectionRange":{"surface":3,"air":0,"submarine":2,"land":0},
        "attackRange":{"surface":3,"air":0,"submarine":2,"land":0},
        "weapons":{"torpedo":{"quantity":9,"range":2}},
        "capabilities":{},
        "position":{"col":8,"row":6},
        "echelon":"START",
        "notes":"SSN classe Swiftsure. Patrulhou a costa continental argentina em busca do porta-aviões 25 de Mayo."
      },
      {
        "id":"RED-LOG-1","name":"RFA Olmeda (petroleiro do GT-PA)","category":"surface",
        "composition":[{"type":"navio_tanque","quantity":1}],
        "stayingPower":4,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":14,"row":2},
        "echelon":"START",
        "notes":"RFA Olmeda. Reabastece o grupo porta-aviões."
      },
      {
        "id":"RED-LOG-2","name":"RFA Appleleaf (petroleiro de escolta)","category":"surface",
        "composition":[{"type":"navio_tanque","quantity":1}],
        "stayingPower":4,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":14,"row":3},
        "echelon":"START",
        "notes":"Reabastece as escoltas do grupo de porta-aviões."
      },
      {
        "id":"RED-MPRA","name":"Nimrod","category":"air",
        "composition":[{"type":"patrulha_maritima","quantity":12}],
        "stayingPower":3,"movement":12,
        "detectionRange":{"surface":4,"air":1,"submarine":2,"land":1},
        "attackRange":{"surface":1,"air":0,"submarine":1,"land":0},
        "weapons":{},
        "capabilities":{"asw":2},
        "position":{"col":19,"row":0},
        "echelon":"START",
        "notes":"Hawker Siddeley Nimrod MR.1/2, base em Ascensão. Reabastecimento em voo estende o alcance a milhares de km."
      },
      {
        "id":"RED-BOM","name":"Vulcan","category":"air",
        "composition":[{"type":"ataque","quantity":6}],
        "stayingPower":2,"movement":12,
        "detectionRange":{"surface":0,"air":0,"submarine":0,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":3},
        "weapons":{"lacm":{"quantity":3,"range":12}},
        "capabilities":{},
        "position":{"col":19,"row":0},
        "echelon":"START",
        "notes":"Avro Vulcan B.2, Operação Black Buck — 6 aeronaves disponíveis, 1 surtida por turno, partindo de Ascensão e dependente da cadeia de Victor. Proibido atacar o continente argentino."
      },
      {
        "id":"RED-TANKER-AIR","name":"Victor K.2","category":"air",
        "composition":[{"type":"reabastecedor","quantity":16}],
        "stayingPower":2,"movement":10,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":19,"row":0},
        "echelon":"START",
        "notes":"Handley Page Victor K.2. Cada missão Black Buck exigiu até 11 petroleiros em cadeia; sustenta uma única missão de Vulcan ou Nimrod por turno."
      },
      {
        "id":"RED-SG-SCR","name":"South Georgia Screen","category":"surface",
        "composition":[{"type":"destroyer","quantity":1},{"type":"fragata","quantity":2}],
        "stayingPower":7,"movement":4,
        "detectionRange":{"surface":2,"air":2,"submarine":1,"land":1},
        "attackRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "weapons":{"ascm":{"quantity":3,"range":6},"mss":{"quantity":3,"range":3}},
        "capabilities":{"navalGun":1,"airDefense":3,"asw":3},
        "position":{"col":16,"row":3},
        "echelon":"START (força avançada)",
        "notes":"HMS Antrim + HMS Plymouth + HMS Brilliant. Força-tarefa de vanguarda — retomou a Geórgia do Sul em 25 abr 1982 (Op. Paraquet)."
      },
      {
        "id":"RED-SG-ICE","name":"HMS Endurance","category":"surface",
        "composition":[{"type":"navio_patrulha","quantity":1},{"type":"helicoptero_ASup","quantity":1}],
        "stayingPower":3,"movement":4,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{"airDefense":1,"asw":1},
        "position":{"col":17,"row":3},
        "echelon":"START (força avançada)",
        "notes":"Navio de vigilância do Antártico. Sua retirada planejada em 1981 é citada como sinal que motivou a invasão argentina."
      },
      {
        "id":"RED-SOF","name":"SAS / SBS","category":"specops",
        "composition":[{"type":"operacoes_especiais","quantity":2}],
        "stayingPower":2,"movement":2,
        "detectionRange":{"surface":0,"air":0,"submarine":0,"land":1},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":2},
        "weapons":{"raid":{"quantity":4,"range":2}},
        "capabilities":{},
        "position":{"col":17,"row":3},
        "hostId":"RED-SG-ICE",
        "stealthy":true,
        "echelon":"START (força avançada)",
        "notes":"Equipes do 22 SAS e do Special Boat Squadron. Reconhecimento e ação direta — Ganso Verde, Monte Kent, Ilha Pebble."
      },
      {
        "id":"RED-LOG-3","name":"RFA Tidespring (petroleiro da Geórgia do Sul)","category":"surface",
        "composition":[{"type":"navio_tanque","quantity":1}],
        "stayingPower":4,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":17,"row":2},
        "echelon":"START (força avançada)",
        "notes":"Acompanha a força avançada da Geórgia do Sul; começa com metade da capacidade."
      },
      {
        "id":"RED-TRAIL","name":"Trail Screen","category":"surface",
        "composition":[{"type":"fragata","quantity":2}],
        "stayingPower":4,"movement":4,
        "detectionRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "attackRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "weapons":{"ascm":{"quantity":2,"range":6}},
        "capabilities":{"navalGun":1,"airDefense":2,"asw":2},
        "position":{"col":15,"row":1},
        "echelon":"TURNO 2",
        "notes":"HMS Ardent + HMS Argonaut. Ardent afundado em 22 mai após apoiar o raid do SAS em Ganso Verde — 22 mortos."
      },
      {
        "id":"RED-LOG-4","name":"RFA Plumleaf (petroleiro do Trail Screen)","category":"surface",
        "composition":[{"type":"navio_tanque","quantity":1}],
        "stayingPower":4,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":15,"row":2},
        "echelon":"TURNO 2",
        "notes":"Petroleiro do segundo escalão, apoia o Trail Screen."
      },
      {
        "id":"RED-TANK","name":"RFA British Tay (petroleiro-lançadeira)","category":"surface",
        "composition":[{"type":"navio_tanque","quantity":1}],
        "stayingPower":5,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":16,"row":1},
        "echelon":"TURNO 2",
        "notes":"Ponte logística com Ascensão. Só reabastece outros petroleiros, nunca navios de combate."
      },
      {
        "id":"RED-LAND-SCR","name":"Landing Screen","category":"surface",
        "composition":[{"type":"fragata","quantity":2}],
        "stayingPower":4,"movement":4,
        "detectionRange":{"surface":2,"air":1,"submarine":1,"land":1},
        "attackRange":{"surface":1,"air":0,"submarine":1,"land":1},
        "weapons":{"ascm":{"quantity":2,"range":6}},
        "capabilities":{"navalGun":1,"airDefense":2,"asw":2},
        "position":{"col":17,"row":0},
        "echelon":"TURNO 3",
        "notes":"HMS Antelope + HMS Ambuscade. Antelope afundado em 24 mai ao tentar desarmar uma bomba não detonada."
      },
      {
        "id":"RED-LPD","name":"Fearless / Intrepid","category":"surface",
        "composition":[{"type":"navio_doca","quantity":2},{"type":"helicoptero_ASup","quantity":4}],
        "stayingPower":14,"movement":2,
        "detectionRange":{"surface":2,"air":1,"submarine":0,"land":2},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "weapons":{},
        "capabilities":{"airDefense":2},
        "position":{"col":17,"row":1},
        "echelon":"TURNO 3",
        "notes":"HMS Fearless + HMS Intrepid (LPD), com 8 helicópteros e embarcações de desembarque. Únicos meios de pôr tropas e viaturas em terra em San Carlos — vulnerabilidade crítica."
      },
      {
        "id":"RED-TROOP","name":"SS Canberra / RMS Queen Elizabeth 2","category":"surface",
        "composition":[{"type":"navio_desembarque","quantity":2}],
        "stayingPower":12,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{"airDefense":1},
        "position":{"col":18,"row":1},
        "echelon":"TURNO 3",
        "notes":"Transatlânticos requisitados que levam a 3ª Brigada de Comandos. As tropas só chegam à praia via Fearless/Intrepid."
      },
      {
        "id":"RED-AC","name":"SS Atlantic Conveyor","category":"surface",
        "composition":[{"type":"navio_logistico","quantity":1},{"type":"helicoptero_ASup","quantity":4}],
        "stayingPower":4,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":18,"row":2},
        "echelon":"TURNO 3",
        "notes":"Porta-contêineres requisitado com Harriers de reposição e helicópteros pesados (Chinook/Wessex). Afundado por Exocet em 25 mai 1982 — 12 mortos e a perda dos Chinook que transportariam a infantaria."
      },
      {
        "id":"RED-HAR-RES","name":"Harriers de reposição (Atlantic Conveyor)","category":"air",
        "composition":[{"type":"caca","quantity":8}],
        "stayingPower":3,"movement":10,
        "detectionRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":18,"row":2},
        "embarked":"RED-AC",
        "echelon":"TURNO 3",
        "notes":"8× Sea Harrier/Harrier GR.3 transportados como reposição. Não operam do Atlantic Conveyor: só podem transferir-se para o Hermes ou o Invincible."
      },
      {
        "id":"RED-3CDO","name":"3ª Brigada de Comandos","category":"land",
        "composition":[{"type":"infantaria","quantity":5},{"type":"bateria_artilharia","quantity":3},{"type":"bateria_ada","quantity":2}],
        "stayingPower":12,"movement":1,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":2},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":2},
        "weapons":{},
        "capabilities":{"navalGun":3,"airDefense":2},
        "position":{"col":18,"row":1},
        "embarked":"RED-TROOP",
        "echelon":"TURNO 3",
        "notes":"40, 42 e 45 Cdo (Royal Marines) + 2 e 3 Para + 29º RA (3 baterias L118) e 2 baterias de defesa antiaérea. Força de assalto inicial — desembarcou em San Carlos em 21 mai 1982."
      },
      {
        "id":"RED-LOG-5","name":"RFA Bayleaf (petroleiro do grupo de desembarque)","category":"surface",
        "composition":[{"type":"navio_tanque","quantity":1}],
        "stayingPower":4,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":18,"row":2},
        "echelon":"TURNO 3",
        "notes":"Apoia o grupo de desembarque — no jogo original tem sete navios a sustentar sozinho."
      },
      {
        "id":"RED-MCM","name":"Esquadrilha Caça-Minas","category":"surface",
        "composition":[{"type":"navio_patrulha","quantity":4}],
        "stayingPower":7,"movement":2,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":18,"row":3},
        "echelon":"TURNO 3",
        "notes":"HMS Junella, Cordella, Farnella, Northella — traineiras convertidas em caça-minas. Abrem caminho para o Estreito de San Carlos."
      },
      {
        "id":"RED-HOSP","name":"Navio-Hospital","category":"surface",
        "composition":[{"type":"navio_logistico","quantity":1}],
        "stayingPower":6,"movement":2,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":19,"row":3},
        "echelon":"TURNO 3",
        "notes":"SS Uganda + navios-ambulância Hecla/Hydra/Herald. Protegido pela Convenção de Genebra — não combate e não pode ser atacado nem usado como escudo."
      },
      {
        "id":"RED-LR","name":"SS Norland / Atlantic Causeway","category":"surface",
        "composition":[{"type":"navio_desembarque","quantity":2}],
        "stayingPower":8,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{"airDefense":1},
        "position":{"col":19,"row":2},
        "echelon":"TURNO 4",
        "notes":"Transportes do escalão de reforço, com a 5ª Brigada de Infantaria. Também dependem dos LPD para desembarcar."
      },
      {
        "id":"RED-5BDE","name":"5ª Brigada de Infantaria","category":"land",
        "composition":[{"type":"infantaria","quantity":3},{"type":"bateria_artilharia","quantity":1},{"type":"bateria_ada","quantity":1}],
        "stayingPower":8,"movement":1,
        "detectionRange":{"surface":1,"air":0,"submarine":0,"land":1},
        "attackRange":{"surface":1,"air":0,"submarine":0,"land":2},
        "weapons":{},
        "capabilities":{"navalGun":2,"airDefense":1},
        "position":{"col":19,"row":2},
        "embarked":"RED-LR",
        "echelon":"TURNO 4",
        "notes":"2º Scots Guards, 1º Welsh Guards e 1/7 Gurkhas + 97ª Bateria/4 RA e 21ª Bateria de defesa antiaérea. Reforço para ampliar a cabeça de praia ou explorar o êxito."
      },
      {
        "id":"RED-TANK-2","name":"RFA British Tamar / British Esk","category":"surface",
        "composition":[{"type":"navio_tanque","quantity":2}],
        "stayingPower":6,"movement":2,
        "detectionRange":{"surface":1,"air":1,"submarine":0,"land":0},
        "attackRange":{"surface":0,"air":0,"submarine":0,"land":0},
        "weapons":{},
        "capabilities":{},
        "position":{"col":19,"row":1},
        "echelon":"TURNO 4",
        "notes":"Segundo par de petroleiros-lançadeira. Só reabastecem outros petroleiros."
      }
    ]
  }
};

if (typeof module !== 'undefined') module.exports = { ORDER_OF_BATTLE };
